#!/usr/bin/env bash
# html-report :: new-report.sh — 创建新的 HTML 报告脚手架
#
# 用法:
#   new-report.sh <name> <output-base-dir>
#
# 在 <output-base-dir>/<name>/ 下创建:
#   <name>.html        (scaffold HTML，首行含 Generated by DeepCodeX 注释)
#   assets/            (用于存放图片与 charts.js 图表逻辑)
#
# 示例:
#   bash ./scripts/new-report.sh market-analysis-2024 ~/reports
#   → 创建 ~/reports/market-analysis-2024/market-analysis-2024.html
#
# 说明:
#   - ECharts/Mermaid 通过 CDN 引用，不本地包含大型 JS 库
#   - 图表初始化逻辑写入 assets/charts.js（由编写者后续创建）
#   - 生成的 HTML 已包含 CSS 变量骨架与基础结构

set -euo pipefail

# --- 参数解析 ---
NAME="${1:-}"
BASE_DIR="${2:-}"

# 校验参数完整性
if [[ -z "$NAME" || -z "$BASE_DIR" ]]; then
  echo "用法: new-report.sh <name> <output-base-dir>" >&2
  echo "" >&2
  echo "  <name>            报告目录名（同时作为 HTML 文件名）" >&2
  echo "  <output-base-dir>  <name>/ 将被创建于此目录下（你的工作目录）" >&2
  exit 1
fi

# 校验 name 合法性（仅允许字母、数字、连字符，不以连字符开头）
if [[ ! "$NAME" =~ ^[a-zA-Z0-9][a-zA-Z0-9-]*$ ]]; then
  echo "错误: <name> 只能包含字母、数字、连字符，且不以连字符开头" >&2
  exit 1
fi

# 解析 output-base-dir 为绝对路径
if [[ "$BASE_DIR" != /* ]]; then
  BASE_DIR="$PWD/$BASE_DIR"
fi

OUT_DIR="$BASE_DIR/$NAME"

# 防止覆盖已存在目录
if [[ -e "$OUT_DIR" ]]; then
  echo "错误: $OUT_DIR 已存在，拒绝覆盖" >&2
  exit 1
fi

# --- 创建目录结构 ---
# assets/ 存放图片与 charts.js；无需 _shared/ 因大型 JS 库走 CDN
mkdir -p "$OUT_DIR/assets"

# --- 生成 scaffold HTML ---
# 首行必须为 Generated by DeepCodeX 注释，用于标识产物来源
cat > "$OUT_DIR/$NAME.html" << 'HTML'
<!-- Generated by DeepCodeX -->
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Report</title>
<style>
  /* === 主题 CSS 变量（编写者按报告调色板修改） === */
  :root {
    --bg: #ffffff;
    --bg2: #f7f7f8;
    --ink: #1a1a1a;
    --muted: #6b7280;
    --rule: #e5e7eb;
    --accent: #2563eb;
    --accent2: #7c3aed;
    --font: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans SC', sans-serif;
    --font-mono: 'SF Mono', Menlo, Consolas, monospace;
    --max: 860px;
  }

  /* === 基础重置 === */
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  html { font-size: 16px; scroll-behavior: smooth; }
  body {
    font-family: var(--font);
    color: var(--ink);
    background: var(--bg);
    line-height: 1.7;
    padding: 2rem 1rem;
  }

  /* === 布局 === */
  article.page { max-width: var(--max); margin: 0 auto; }
  header.page-header { margin-bottom: 3rem; padding-bottom: 1.5rem; border-bottom: 1px solid var(--rule); }
  header.page-header h1 { font-size: 2.25rem; line-height: 1.2; margin-bottom: 0.5rem; }
  main { margin-bottom: 4rem; }
  section { margin-bottom: 2.5rem; }
  h2 { font-size: 1.6rem; margin-bottom: 1rem; padding-bottom: 0.3rem; border-bottom: 1px solid var(--rule); }
  h3 { font-size: 1.25rem; margin: 1.5rem 0 0.75rem; }
  h4 { font-size: 1.05rem; margin: 1.25rem 0 0.5rem; }
  p { margin-bottom: 1rem; }

  /* === 引用与来源 === */
  sup a { color: var(--accent); text-decoration: none; font-size: 0.75em; font-weight: 600; }
  footer .sources { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid var(--rule); }
  footer .sources h2 { font-size: 1.1rem; border: none; margin-bottom: 0.75rem; }
  footer .sources ol { padding-left: 1.2rem; font-size: 0.85rem; color: var(--muted); }
  footer .sources li { margin-bottom: 0.5rem; overflow-wrap: break-word; }

  /* === 打印 === */
  @media print {
    body { padding: 0; }
    section { page-break-inside: avoid; }
    h2 { page-break-after: avoid; }
  }
</style>
</head>
<body>
  <article class="page">
    <header class="page-header">
      <h1>报告标题</h1>
      <p class="subtitle">副标题或一句话简介</p>
    </header>
    <main>
      <section>
        <h2>章节 1</h2>
        <p>正文内容写在这里。</p>
      </section>
    </main>
    <footer>
      <div class="sources">
        <h2>来源</h2>
        <ol></ol>
      </div>
    </footer>
  </article>

  <!-- ECharts/Mermaid CDN（按需取消注释） -->
  <!-- <script src="https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script> -->
  <!-- <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script> -->
  <!-- 图表初始化逻辑（外部文件，按需创建） -->
  <!-- <script src="./assets/charts.js"></script> -->
</body>
</html>
HTML

# --- 输出结果 ---
echo "✔ 已创建: $OUT_DIR/$NAME.html"
echo "✔ 已创建: $OUT_DIR/assets/  (放置图片与 charts.js)"
echo ""
echo "后续步骤:"
echo "  1. 编辑 $NAME.html — 填充标题与正文内容"
echo "  2. 按需取消注释 ECharts/Mermaid CDN 引用"
echo "  3. 创建 $OUT_DIR/assets/charts.js 编写图表逻辑"
echo "  4. 图片放入 $OUT_DIR/assets/，用相对路径引用"
echo "  5. 浏览器打开 $NAME.html 即可阅读"
