#!/usr/bin/env bash
# html-deck :: new-deck.sh — 创建新的 HTML 演示文稿脚手架
#
# 用法:
#   new-deck.sh <name> <output-base-dir>
#
# 在 <output-base-dir>/<name>/ 下创建:
#   <name>.html        (scaffold HTML，首行含 Generated by DeepCodeX 注释)
#   assets/            (用于存放生成的图片)
#   _shared/           (共享资产: base.css + runtime.js + themes/)
#
# 示例:
#   bash ./scripts/new-deck.sh my-talk ~/presentations
#   → 创建 ~/presentations/my-talk/my-talk.html

set -euo pipefail

# --- 参数解析 ---
NAME="${1:-}"
BASE_DIR="${2:-}"

# 校验参数完整性
if [[ -z "$NAME" || -z "$BASE_DIR" ]]; then
  echo "用法: new-deck.sh <name> <output-base-dir>" >&2
  echo "" >&2
  echo "  <name>            演示文稿目录名（同时作为 HTML 文件名）" >&2
  echo "  <output-base-dir>  <name>/ 将被创建于此目录下（你的工作目录）" >&2
  exit 1
fi

# 校验 name 合法性（仅允许字母、数字、连字符）
if [[ ! "$NAME" =~ ^[a-zA-Z0-9][a-zA-Z0-9-]*$ ]]; then
  echo "错误: <name> 只能包含字母、数字、连字符，且不以连字符开头" >&2
  exit 1
fi

# 解析 skill 根目录（脚本位于 <skill>/scripts/，父目录即 skill 根）
HERE="$(cd "$(dirname "$0")/.." && pwd)"

# 解析 output-base-dir 为绝对路径
if [[ "$BASE_DIR" != /* ]]; then
  BASE_DIR="$PWD/$BASE_DIR"
fi

OUT_DIR="$BASE_DIR/$NAME"

# 防止覆盖已存在目录
if [[ -e "$OUT_DIR" ]]; then
  echo "错误: $OUT_DIR 已存在，拒绝覆盖" >&2
  exit 1
fi

# --- 创建目录结构 ---
mkdir -p "$OUT_DIR/assets" \
         "$OUT_DIR/_shared/themes"

# --- 复制共享资产 ---
# 复制基础样式与运行时脚本
for f in base.css runtime.js; do
  if [[ -f "$HERE/assets/$f" ]]; then
    cp "$HERE/assets/$f" "$OUT_DIR/_shared/"
  else
    echo "警告: 缺少 $HERE/assets/$f，请检查 skill 完整性" >&2
  fi
done

# 复制默认主题（light + dark）
for t in light dark; do
  if [[ -f "$HERE/assets/themes/$t.css" ]]; then
    cp "$HERE/assets/themes/$t.css" "$OUT_DIR/_shared/themes/"
  fi
done

# --- 生成 scaffold HTML ---
# 首行必须为 Generated by DeepCodeX 注释，用于标识产物来源
cat > "$OUT_DIR/$NAME.html" << 'HTML'
<!-- Generated by DeepCodeX -->
<!DOCTYPE html>
<html lang="zh-CN" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Deck</title>
<link rel="stylesheet" href="./_shared/base.css">
<link id="theme-link" rel="stylesheet" href="./_shared/themes/light.css">
</head>
<body data-themes="light,dark" data-theme-base="./_shared/themes/">
<div class="deck">

  <!-- 1. 封面 -->
  <section class="slide" data-title="封面" data-anim="fade-up">
    <p class="kicker">演示 · 2026</p>
    <h1 class="h1">演示文稿标题</h1>
    <p class="lede">副标题或一句话简介</p>
    <div class="deck-footer">
      <span class="dim2">作者</span>
      <span class="slide-number" data-current="1" data-total="3"></span>
    </div>
    <div class="notes">封面页口播稿：大家好，今天分享的主题是…</div>
  </section>

  <!-- 2. 正文 -->
  <section class="slide" data-title="内容" data-anim="fade-up">
    <p class="kicker">章节</p>
    <h2 class="h2">正文标题</h2>
    <p>正文内容写在这里。</p>
    <div class="notes">本页要点提示。</div>
  </section>

  <!-- 3. 结语 -->
  <section class="slide center" data-title="结语" data-anim="fade-up">
    <h1 class="h1"><span class="gradient-text">谢谢</span></h1>
    <div class="notes">结语页：感谢观看，欢迎提问。</div>
  </section>

</div>
<script src="./_shared/runtime.js"></script>
</body>
</html>
HTML

# --- 输出结果 ---
echo "✔ 已创建: $OUT_DIR/$NAME.html"
echo "✔ 已创建: $OUT_DIR/assets/  (放置生成的图片)"
echo "✔ 已创建: $OUT_DIR/_shared/base.css"
echo "✔ 已创建: $OUT_DIR/_shared/runtime.js"
echo "✔ 已创建: $OUT_DIR/_shared/themes/ (light.css, dark.css)"
echo ""
echo "后续步骤:"
echo "  1. 编辑 $NAME.html — 填充主题与内容"
echo "  2. 如需更多主题，从 $HERE/assets/themes/ 复制到 $OUT_DIR/_shared/themes/"
echo "  3. 生成的图片放入 $OUT_DIR/assets/"
echo "  4. 浏览器打开 $NAME.html 即可放映"
